### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by N3tW0rk418** [ghewgill/nwr#1]
There were SEVERAL errors related to compiling with GCC4.3 but I was able to get past them. However I was not able to get past the error regarding this code;

eas_decode.cpp: fips.inc

fips.inc: ../emwin/data/county.dump fips2inc.pl
        perl fips2inc.pl ../emwin/data/county.dump >$@

Any suggestions? I would really like to get this integrated with our repeater linking system.

**Comment by ghewgill** [comment]
I searched through my archives and found a few missing files including the county.dump file needed for that step of the build. I have updated the source for modern compilers and included the missing files.
