### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by luesjo12** [ghewgill/nwr#2]
After compiling and configuring, trying to run make or make install fail with this error: 

g++ -DHAVE_CONFIG_H -I. -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include    -g -Wall -Werror -MT capture.o -MD -MP -MF .deps/capture.Tpo -c -o capture.o capture.cpp
capture.cpp: In constructor ‘Mp3Writer::Mp3Writer(const char*, int, int, int)’:
capture.cpp:116:21: error: ‘pipe’ was not declared in this scope
     if (pipe(pipeout) != 0) {
                     ^
capture.cpp:120:18: error: ‘fork’ was not declared in this scope
     child = fork();
                  ^
capture.cpp:126:27: error: ‘dup2’ was not declared in this scope
         dup2(pipeout[0], 0);
                           ^
capture.cpp:127:25: error: ‘close’ was not declared in this scope
         close(pipeout[1]);
                         ^
capture.cpp:128:110: error: ‘execl’ was not declared in this scope
         execl("/usr/local/bin/lame", "lame", "-r", "-m", "m", "-s", "11.025", "-x", "-b", "16", "-", fn, NULL);
                                                                                                              ^
capture.cpp:132:21: error: ‘close’ was not declared in this scope
     close(pipeout[0]);
                     ^
capture.cpp: In destructor ‘virtual Mp3Writer::~Mp3Writer()’:
capture.cpp:141:14: error: ‘close’ was not declared in this scope
     close(out);
              ^
capture.cpp: In member function ‘virtual void Mp3Writer::write(const void*, size_t)’:
capture.cpp:154:5: error: ‘::write’ has not been declared
     ::write(out, buf, n);
     ^~
capture.cpp: In function ‘void eas_deactivate()’:
capture.cpp:248:18: error: ‘fork’ was not declared in this scope
         if (fork() == 0) {
                  ^
Makefile:464: recipe for target 'capture.o' failed
make: *** [capture.o] Error 1

All help would be appreciated.

**Comment by ghewgill** [comment]
It looks like there should be an `#include <unistd.h>` in that file. Add that and see if it helps for your system. You may need to add the same file to other source files, too.

**Comment by luesjo12** [comment]
After trying to run make install after adding #include <unistd.h> I got numerous errors, so I decided to redownload the whole folder and then add the line to the .cpp files. While running make check, I now get this error: 

make check
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure --no-create --no-recursion
./configure: line 2074: AM_INIT_AUTOMAKE: command not found
./configure: line 2076: syntax error near unexpected token `config.h'
./configure: line 2076: `AM_CONFIG_HEADER(config.h)'
Makefile:343: recipe for target 'config.status' failed
make: *** [config.status] Error 2

**Comment by ghewgill** [comment]
Sorry, I don't know enough about autotools to be able to diagnose the problem you're seeing there. You can build the code whatever way you like, you don't have to use the built-in configure script if it's not working on your system.
